---

- name: Install exa
  hosts: all
  become: yes

  tasks:
  - name: Install exa
      become_user: ecloaiza
      command: "curl -sL https://github.com/ogham/exa/releases/download/v0.10.2/exa-linux-x86_64-v0.10.2.zip -o /tmp/exa.zip && unzip /tmp/exa.zip -d /tmp && mv /tmp/exa-linux-x86_64 /usr/local/bin/exa && chmod +x /usr/local/bin/exa"
        
    - name: Run YADM install script
      shell: /opt/yadm/yadm bootstrap
      args:
        chdir: /opt/yadm
      when: yadm_clone.changed