---
- name: Install exa
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - unzip

    - name: Download exa
      get_url:
        url: "https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip"
        dest: /tmp/exa.zip

    - name: Unzip exa
      unarchive:
        src: /tmp/exa.zip
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/exa

    - name: Make exa executable
      file:
        path: /usr/local/bin/exa
        mode: '+x'

    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - curl

    - name: Clone YADM repository
      git:
        repo: https://github.com/elikesbikes/linux_dotfiles
        dest: /home/ecloaiza
        update: no

    - name: Run YADM bootstrap script
      command: /home/ecloaiza/.yadm/bootstrap