---
- name: Install exa
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - unzip

    - name: Download exa      
      command: "curl -fLo /tmp/exa.zip https://github.com/ogham/exa/releases/download/v0.10.0/exa-linux-x86_64-v0.10.0.zip"
        

    - name: Unzip exa
      unarchive:
        src: /tmp/exa.zip
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/exa
        

    - name: Make exa executable
      file:
        path: /usr/local/bin/bin/exa
        mode: '+x'


     