---
- name: Install exa
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - unzip
        - git
        - curl

    - name: Install dnf-utils
      package:
        name: dnf-utils
        state: present

    - name: Install exa
      package:
        name: exa
        state: present

    - name: Clone YADM repository
      git:
        repo: https://github.com/elikesbikes/linux_dotfiles
        dest: /home/ecloaiza
        update: no

    - name: Run YADM bootstrap script
      command: /home/ecloaiza/.yadm/bootstrap


     